684468/ssafy/October/DB/오프라인/Many_to_one/CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name = 'change_password'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

684468/ssafy/October/DB/오프라인/Many_to_one/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
   path('login/', views.login, name = 'login'),
   path('logout/', views.logout, name = 'logout'),
   path('signup/', views.signup, name = 'signup'), # 회원가입
   # request에 이미 로그인 되어있는 유저의 데이터
   path('delete/', views.delete, name = 'delete'), # 회원탈퇴
   path('update/', views.update, name = 'update'), # 회원정보변경
]

684468/ssafy/October/DB/오프라인/Many_to_one/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    # 전체 게시글 조회
    path('', views.index, name = 'index'),
    # 단일 게시글 조회(detail 페이지)
    # variable routing ---> 단순히 조회 목적
    # 1. views.py 함수에서 pk를 매개변수
    # 2. url naming pattern article.pk
    path('<int:pk>/', views.detail, name = 'detail'),
    # 페이지 랜더링 + 리다이렉트
    path('create/', views.create, name = 'create'),
    # variable routing ---> 조회 후 삭제, 조회 후 수정
    path('<int:pk>/delete/', views.delete, name = 'delete'),
    # 페이지 렌더링 + 리다이렉트
    path('<int:pk>/update/', views.update, name = 'update'),
    # 댓글 생성 url
    path('<int:pk>/comments/', views.comments_create, name = 'comments_create'),

    path('<int:article_pk>/comments/<int:comment_pk>/delete/',
         views.comments_delete,
         name = 'comments_delete'
    ),
    path('<int:article_pk>/likes/', views.likes, name = 'likes'),
]

684468/ssafy/October/DB/오프라인/Many_to_one/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Article(models.Model):
  # settings.py의 사용자 모델을 참조
  # on_delete=models.CASCADE ---> 연결된 사용자가 삭제되면 게시글도 함께 삭제
  # 사용자와 게시글의 관계(Many-to-one)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  # M과N관계
  # article_set으로 접근하게 되면 충돌 발생 그래서 related_name = 'like_articles'를 지정
  # User에서 작성한 게시글들: user.article_set
  # User에서 좋아요 누른 게시글들 : user.like_articles
  like_users = models.ManyToManyField(
    settings.AUTH_USER_MODEL, related_name='like_articles'
  )
  title = models.CharField(max_length=20)
  content = models.TextField()
  # 이미지를 넣지않아도 게시글이 생성이 되게
  image = models.ImageField(blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
  # 게시글과 댓글 간의 관계(Many-to-one)
  article = models.ForeignKey(Article, on_delete=models.CASCADE)
  # 작성자와 댓글 간의 관계(Many-to-one)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  content = models.CharField(max_length=200)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

# ORM
# : python 코드를 SQL 쿼리로 변환해주는 도구
# 왜 ORM을 쓰냐?
# 우리가 사용하는 Django는 python, DB는 SQL
# QuerySet API  
# : 이 구문을 사용하면 데이터베이스에 접근하고 조작할 수 있다


# Create
'''
# 첫 번째 방법

article = Article()
article.title = ‘first’
article.content = ‘hello’
article.save()

Article.objects.all()

# 두 번째 방법

article = Article(title = ‘second’, content = ‘hello’)
article.save()

Ariticle.objects.all()

# 세 번째 방법

Article.objects.create(title = ‘third’, content = ‘byebye’)

Ariticle.objects.all()
'''

# 1번, 2번 // 3번 : save 호출을 따로 하는지 안하는지
# 3번 방법은 지양, save() 호출전에 미리 데이터를 검증하고 그다음에 save() 해야 한다
# best 1번 가장 안정적 
# 검증단계 ---> 유효성 검사... 등등

# Read
'''
# 전체 데이터 조회
Aritcle.objects.all()


# 특정 조건 데이터 조회(filter)
Article.objects.filter(title = ‘first’)
Article.objects.filter(content__contains=’hel’)
Article.objects.filter(title__startswith=’f’)

# 단일 데이터 조회(get)
Article.objects.get(pk = 1)
Article.objects.get(content = ‘hello word’)

# 찾는 객체가 없으면 예외발생
# 찾는 객체가 두개 이상 있으면 예외 발생

# —> 고유성을 보장하는 조회
'''

# Update
'''
article = Article.objects.get(pk = 1)
article.title = ‘first1’
article.save()
'''

# delete
'''
article = Article.objects.get(pk = 1)
article.delete()
Article.objects.get(pk = 1)
# —> 예외 발생
'''

# 추가 QuerySet API 는 구글에 Django QuerySet API 검색 ---> 공식문서

684468/ssafy/October/DB/오프라인/Many_to_one/articles/forms.py
from django import forms
from .models import Article, Comment

# form 태그, django ModelForm의 차이?
# 사용자로부터 입력받은 데이터를 DB에 저장하는지 안하는지?
# form 태그 사용해서도 DB 저장 가능, 단 수동으로 구현해야 함.
# ModelForm을 왜 쓸까?? 편하고 효율성이 좋아서 + 유효성 검사에 용이해서

class ArticleForm(forms.ModelForm):
  # 모델폼의 설계 구조
  # class Meta: 폼의 기본 구조를 자동으로 생성 ---> 세부 조정 가능(어떤 필드, 위젯)
  class Meta:
    model = Article
    # fields = ('title', 'content', 'created_at', 'updated_at', 'image', )
    # fields = '__all__'
    fields = (
      'title',
      'content',
    )

class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ('content', )

684468/ssafy/October/DB/오프라인/Many_to_one/articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# 현재 디렉토리의 models.py로부터 Article 모델을 가져오겠다.
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


def index(request):
  # QuerySet API ---> 전체 데이터 조회 : Aritlce.objects.all()
  articles = Article.objects.all()
  context = {
    'articles' : articles,
  }
  return render(request, 'articles/index.html', context)

# 단일 게시글 페이지 렌더링 
def detail(request, pk):
  # QuerySet API ---> 단일 데이터 조회 : get
  article = Article.objects.get(pk = pk)
  comment_form = CommentForm()

  # comment_set --> 역참조
  # 게시글에 달린 모든 댓글을 가져오기 위해서(역참조)
  comments = article.comment_set.all()

  context = {
    'article' : article,
    'comment_form' : comment_form,
    'comments' : comments,
  }

  return render(request, 'articles/detail.html', context)

# 페이지 렌더링
'''
def new(request):
  return render(request, 'articles/new.html')
'''

# render와 redirect차이
# render : 사용자에게 새로운 페이지를 보여줄 때 사용
# redirect : 데이터 처리 후 다른 페이지로 이동 할때 사용

'''
# 페이지 리다이렉트(데이터를 받아서 DB에 저장 - POST방식)
def create(request):
  # Create 2번, 3번방법 절대 x
  # GET방식은 데이터가 url에 노출 ---> 데이터를 조회, 검색
  # POST방식은 보안성(csrf 토큰) ---> 데이터를 생성, 수정, 삭제

  title = request.POST.get('title')
  content = request.POST.get('content')

  # 저장 ---> 2번 방법(코드가 간결하면서 안정성)
  article = Article(title = title, content = content)
  # 데이터 관리(저장) 원칙 : 안정성
  # save하기전에 유효성 검사!!
  article.save()

  # 게시글을 생성(데이터가 변경됐다)하고, 생성버튼 누르고 어떤 페이지로 이동할건가??
  # 클라이언트가 GET 요청을 한번 더 보내도록 한다(redirect).
  # 데이터가 변경 되었을 때 경로에 요청
  return redirect('articles:detail', article.pk)
'''
@login_required
def create(request):
  # 내가 게시글 생성 버튼을 눌렀을 때
  if request.method == 'POST':
    form = ArticleForm(request.POST, request.FILES)
    # 유효성 검사 대표적인 2가지
    # 1. 모든 필수 필드가 채워져 있는지.
    # 2. 입력된 데이터가 필드의 조건(ex 데이터 형식, 길이 제한)을 만족하는지.
    # 3. .....
    if form.is_valid():
      # 바로 DB에 자동으로 저장 ---> request.user정보(수동으로 저장) ---> (commit=False)
      article = form.save(commit=False)
      # request.user ---> 로그인한 사용자
      article.user = request.user
      article.save() # 최종적으로 DB에 저장
      # DB에 새 게시글이 저장 되었다.
      return redirect('articles:detail', article.pk)

  # 게시글 생성 버튼을 누르기 전 또는 다른 버튼 눌렀을 때(다른 method일때)
  else:
    form = ArticleForm()
  # 1. 유효성 검사 통과하지 못한경우(에러와 함께 폼 다시 표시)
  # 2. GET 요청인 경우(빈 폼 표시)
  context = {
    'form': form,
  }
  return render(request, 'articles/create.html', context)

# 단일 게시글 조회 후 삭제 
# 데이터 변경 ---> redirect
@login_required
def delete(request, pk):
  article = Article.objects.get(pk = pk)
  # request.user : 로그인한 사용자
  # article.user : 게시글 작성자
  if request.user == article.user:
    article.delete()
  # 여기서 request는 무슨 방식일까? POST방식 왜?(DB 변경)
  return redirect('articles:index')

'''
# 페이지 렌더링(create와 차이 : 기존에 있던 게시글을 조회)
def edit(request, pk):
  article = Article.objects.get(pk = pk)
  context = {
    'article' : article
  }
  return render(request, 'articles/edit.html', context)

# 페이지 리다이렉트(create와 차이 : 기존에 있던 게시글을 변경)
def update(request, pk):
  article = Article.objects.get(pk = pk)

  article.title = request.POST.get('title')
  article.content = request.POST.get('content')

  article.save()

  return redirect('articles:detail', article.pk)

'''
# 단일 게시글 조회하고 변경, 저장
@login_required
def update(request, pk):
  # 조회 먼저 하고
  article = Article.objects.get(pk = pk)
  # 로그인한 유저와 게시글 작성자가 같을떄 update를 할 수 있다.
  if request.user == article.user:
    if request.method == 'POST':
      # 기존 게시글의 데이터를 미리 채운다(instance = article)
      form = ArticleForm(request.POST, request.FILES, instance = article)
      if form.is_valid():
        form.save()
        return redirect('articles:detail', article.pk)
    # 변경 버튼 누르기전 또는 다른 버튼 눌렀을때
    else:
      form = ArticleForm(instance = article)
  else:
    return redirect('articles:index')

  context = {
    # 기존에 존재했던 데이터
    'article' : article,
    'form' : form,
  }

  return render(request, 'articles/update.html', context)

@login_required
def comments_create(request, pk):
  # 게시글 조회
  article = Article.objects.get(pk=pk)
  comment_form = CommentForm(request.POST)
  # 댓글 유효성 검사
  if comment_form.is_valid():
    # 댓글을 바로 DB에 바로 저장?? ---> 2개 수동으로 저장
    comment = comment_form.save(commit=False)
    comment.article = article # 첫 번째 : 게시글의 외래키
    comment.user = request.user # 두 번째 : 로그인한 사용자(request.user)
    comment.save() # DB에 수동으로 저장
    return redirect('articles:detail', article.pk)
  # 유효성검사에 실패
  context = {
    'article' : article,
    'comment_form' : comment_form
  }
  return render(request, 'articles/detail.html', context)

@login_required
def comments_delete(request, article_pk, comment_pk):
  comment = Comment.objects.get(pk=comment_pk)
  if request.user == comment.user:
    comment.delete()
  
  return redirect('articles:detail', article_pk)

@login_required
def likes(request, article_pk):
  article = Article.objects.get(pk=article_pk)
  if request.user in article.like_users.all():
    article.like_users.remove(request.user)
  else:
    article.like_users.add(request.user)
  return redirect('articles:index')

684468/ssafy/October/DB/오프라인/Many_to_one/articles/templates/articles/create.html
{% extends "base.html" %}


{% block content %}
  <h1>게시글 생성</h1>
  {% comment %} form 태그로 POST방식 --->  {% endcomment %}
  {% comment %} 1. url의 create {% endcomment %}
  {% comment %} 2. views.py create함수의 request {% endcomment %}

  {% comment %} enctype = "multipart/form-data" ---> 폼 데이터와 함께 파일(이미지, 문서...)을 서버에 전송할수 있다. {% endcomment %}
  <form action="{% url "articles:create" %}" method = "POST" enctype = "multipart/form-data">
    {% comment %} csrf 토큰 : 보안 토큰(POST방식) {% endcomment %}
    {% csrf_token %}
    {% comment %} form.as_table, form.as_ul, form.as_div {% endcomment %}
    {{ form.as_p }}
    

    {% comment %} for = "title" 과 id = "title" 연관 {% endcomment %}
    {% comment %} name = "title"과 request.POST.get('title') {% endcomment %}
    {% comment %}     
    <div>   
      <label for="title">Title : </label>
      <input type="text" name = "title" id = "title">
    </div>
      
    <div> 
      <label for="content">Content : </label>
      <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>
    {% endcomment %}
    
    <input type="submit">
  </form>


{% endblock content %}

684468/ssafy/October/DB/오프라인/Many_to_one/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}

  <h2> DETAIL </h2>
  {% comment %} DTL 변수 {% endcomment %}
  <h3>{{article.pk}} 번째 게시글</h3>

  <hr>

  <p>제목 : {{article.title}}</p>
  <p>내용 : {{article.content}}</p>
  <p>작성 시각 : {{article.created_at}}</p>
  <p>수정 시각 : {{article.updated_at}}</p>

  <hr>
  
  {% if request.user == article.user %}
    {% comment %} 변경 버튼, variabel routing이기 떄문에 article.pk {% endcomment %}
    <a href="{% url "articles:update" article.pk%}">게시글 수정</a>
    <hr>
    <form action="{% url "articles:delete" article.pk %}" method = "POST">
      {% csrf_token %}
      {% comment %} value는 초기값 초기 페이지에 뜨는 글을 DELETE로 하겠다 {% endcomment %}
      <input type="submit" value="DELETE">
    </form>
  {% endif %}

  {% comment %} image 는 있을 수도 있고, 없을 수도 있다. DTL의 조건문{% endcomment %}
  {% if article.image %}
    {% comment %} src에는 업로드된 이미지의 URL 을 넣어야 한다. {% endcomment %}
    <img src="{{article.image.url}}" alt="img">
  {% endif %}
 
  <h4>댓글 목록</h4>
  <ul>
    {% for comment in comments%}
      <li>
        {{comment.user}} - {{comment.content}}
        {% comment %} 현재 로그인한 유저와 댓글을 단 유저가 같을때 삭제 버튼이 보인다 {% endcomment %}
        {% if request.user == comment.user %}{% endif %}
          <form action="{% url "articles:comments_delete" article.pk comment.pk%}" method = "POST">
           {% csrf_token %}
           <input type="submit" value = "삭제">
          </form>
      </li>
    {% endfor %}
  </ul>

  <hr>

  <h4>댓글 생성</h4>
  <form action="{% url 'articles:comments_create' article.pk%}" method="POST">
    {% csrf_token %}
    {{comment_form}}
    <input type="submit">
  </form>


  {% comment %} back버튼(home버튼)  {% endcomment %}
  {% comment %} url naming pattern {% endcomment %}
  <a href="{% url "articles:index" %}">Home</a>
{% endblock content %}

684468/ssafy/October/DB/오프라인/Many_to_one/articles/templates/articles/index.html
{% extends "base.html" %}
{% comment %} 템플릿 상속 {% endcomment %}

{% load static %}

{% block content %}
  <h3>안녕하세요. {{user.username}}님</h3>
  <h1>게시판</h1>

  {% comment %} 사용자 인증이 되어 있을 때(로그인 되었을 때) {% endcomment %}
  {% if request.user.is_authenticated %}
  
    <hr>
    <a href="{% url "articles:create" %}"> 게시글 생성 </a>
    <hr>
  
    <form action="{% url "accounts:logout" %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="로그 아웃">
    </form>

    <form action="{% url "accounts:delete" %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="회원 탈퇴">
    </form>
    
    <hr>
    <a href="{% url "accounts:update" %}">회원 정보 수정</a>
    <hr>

  {% else %}
    <a href="{% url "accounts:login" %}">로그인</a>
    <a href="{% url "accounts:signup" %}">회원 가입</a>
  {% endif %}
  {% comment %} <img src="{% static "django_structure.png" %}" alt="django"> {% endcomment %}




  {% comment %} DTL 반복문 {% endcomment %}
  {% for article in articles%}
  {% comment %} DTL 변수 {% endcomment %}
  {% comment %} {{article.pk}} ---> 객체.속성 {% endcomment %}
    <p>글 id : {{article.pk}} </p>
    {% comment %} url naming pattern {% endcomment %}
    <a href="{% url "articles:detail" article.pk%}">
      <p>글 제목 : {{article.title}} </p>
    </a>

    <p>글 내용 : {{article.content}} </p>
    
    <form action="{% url "articles:likes" article.pk %}" method = "POST">
      {% csrf_token %}
      {% comment %} 만약 좋아요를 이미 눌렀다면 ㅇ좋아요 취소 {% endcomment %}
      {% if request.user in article.like_users.all %}
      <input type="submit" value="좋아요 취소">
      {% else %}
      <input type="submit" value="좋아요">
      {% endif %}
    </form>
  {% endfor %}


{% endblock content %}

684468/ssafy/October/DB/오프라인/Many_to_one/articles/templates/articles/update.html
{% extends "base.html" %}

{% block content %}
  <h1> EDIT </h1>
  {% comment %} variable routing ---> article.pk {% endcomment %}
  {% comment %} value는 초기값 {% endcomment %}
  {% comment %} 초기글(content) DTL {% endcomment %}

  <form action="{% url "articles:update" article.pk%}" method = "POST" enctype = "multipart/form-data">
    {% csrf_token %}
    {{ form.as_p}}  
    {% comment %} <div> 
      <label for="title">Title : </label>   
      <input type="text" name = "title" id = "title" value="{{article.title}}">
    </div>      
    <div> 
      <label for="content">Content : </label>      
      <textarea name="content" id="content" cols="30" rows="10">{{article.content}}</textarea>
    </div> {% endcomment %}
    <input type="submit">
  </form>

  {% comment %} 취소버튼 {% endcomment %}
  <a href="{% url "articles:index" %}"> [Home] </a>

{% endblock content %}